### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by eskilfogelstrom** [charleserious/fed25sto#32]
Great job! Code is clean and easy to read.

Some constructive feedback
-
This IIEF (Immediately Invoke Function Execution) is a nice trick to scope things. However it's now possible in JS to use modules already in the browser which are already scoped. Check out https://javascript.info/modules-intro
https://github.com/charleserious/fed25sto/blob/f2b63a06609ec8be63a899f6578fae9417c70d5b/05-if-this-then-that/number-guessing/index.js#L3

Instead of passing in a class as a string consider passing in what's known as an [enum](https://www.sohamkamani.com/javascript/enums/). That way you if you ever change your class names or add more you only have one place to do it in.
https://github.com/charleserious/fed25sto/blob/f2b63a06609ec8be63a899f6578fae9417c70d5b/05-if-this-then-that/number-guessing/index.js#L59
```js
const RESULT_STATES = {
    CORRECT: 'guess__result_success',
    INCORRECT: 'guess__result_failed',
    ERROR: 'guess__result_angry'
};

renderGuessResult('Congratulations you did it!', RESULT_STATES.CORRECT);
// ...
renderGuessResult("NO! TOO BIG!", RESULT_STATES.INCORRECT);
// ...
renderGuessResult("WHAT HAVE YOU DONE!!!!!!", RESULT_STATES.INCORRECT);
```

**Comment by charleserious** [comment]
Yeah, thank you so much for reading through this.
Yeah, you make the point of using `type="module"` to scope things and not to pollute global env.
And I don't know we already have enum in JS, I think I'm kinda out of updates now.
Thank you so much
